# Generated by Django 5.2.1 on 2025-06-03 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('motDePasseHash', models.CharField(max_length=255)),
                ('photoProfil', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('dateInscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('tentativesConnexion', models.IntegerField(default=0)),
                ('estBloque', models.BooleanField(default=False)),
            ],
        ),
    ]
