# Generated by Django 5.2.1 on 2025-06-22 22:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('espace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='reservations.espace')),
                ('membre', models.ForeignKey(limit_choices_to={'role': 'membre'}, on_delete=django.db.models.deletion.CASCADE, to='reservations.utilisateur')),
            ],
        ),
    ]
