# Generated by Django 5.2.1 on 2025-06-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='espace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='espaces/'),
        ),
        migrations.AddField(
            model_name='espace',
            name='nombre_avis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='espace',
            name='note_moyenne',
            field=models.FloatField(default=0.0),
        ),
    ]
