# Generated by Django 5.2.1 on 2025-06-25 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_espace_image_espace_nombre_avis_espace_note_moyenne'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
