# Generated by Django 5.2.1 on 2025-06-26 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservation_montant_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reduction_pourcent',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='services_utilises',
        ),
    ]
