# Generated by Django 5.2.1 on 2025-06-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_reservation_qr_code_reservation_reduction_pourcent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payee',
            field=models.BooleanField(default=False),
        ),
    ]
