# Generated by Django 5.2.1 on 2025-06-26 03:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_reservation_payee'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
